# Generated by Django 3.1.2 on 2020-11-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fav_quote',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
