# Generated by Django 3.1.2 on 2020-11-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201123_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pen_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
