# Generated by Django 3.1.2 on 2020-11-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20201025_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='thurahtet', max_length=12),
            preserve_default=False,
        ),
    ]
