# Generated by Django 3.1.2 on 2020-11-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20201110_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewcount',
            name='views_for_post',
        ),
    ]
