# Generated by Django 3.1.2 on 2020-11-11 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_remove_viewcount_views_for_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='view',
            old_name='viewed',
            new_name='created',
        ),
    ]
