# Generated by Django 3.1.2 on 2020-11-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20201111_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
