# Generated by Django 3.1.2 on 2020-11-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20201113_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='ip',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
    ]
