# Generated by Django 3.1.2 on 2020-12-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20201121_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default='thurahtet', max_length=12),
            preserve_default=False,
        ),
    ]
